name: Keep Render Server Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: https://stockwise-24nq.onrender.com/
          curl -sSf 
